/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IAllowedListInterface extends utils.Interface {
  functions: {
    "addToAllowedList(address)": FunctionFragment;
    "checkAllowedList(address)": FunctionFragment;
    "isInAllowedList(address)": FunctionFragment;
    "removeFromAllowedList(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addToAllowedList"
      | "checkAllowedList"
      | "isInAllowedList"
      | "removeFromAllowedList"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addToAllowedList",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "checkAllowedList",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isInAllowedList",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFromAllowedList",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "addToAllowedList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkAllowedList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInAllowedList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFromAllowedList",
    data: BytesLike
  ): Result;

  events: {
    "AddToAllowedList(address)": EventFragment;
    "RemoveFromAllowedList(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddToAllowedList"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RemoveFromAllowedList"): EventFragment;
}

export interface AddToAllowedListEventObject {
  _address: string;
}
export type AddToAllowedListEvent = TypedEvent<
  [string],
  AddToAllowedListEventObject
>;

export type AddToAllowedListEventFilter =
  TypedEventFilter<AddToAllowedListEvent>;

export interface RemoveFromAllowedListEventObject {
  _address: string;
}
export type RemoveFromAllowedListEvent = TypedEvent<
  [string],
  RemoveFromAllowedListEventObject
>;

export type RemoveFromAllowedListEventFilter =
  TypedEventFilter<RemoveFromAllowedListEvent>;

export interface IAllowedList extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IAllowedListInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addToAllowedList(
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    checkAllowedList(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isInAllowedList(
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeFromAllowedList(
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addToAllowedList(
    _address: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  checkAllowedList(
    _address: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isInAllowedList(
    _address: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeFromAllowedList(
    _address: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addToAllowedList(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    checkAllowedList(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isInAllowedList(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeFromAllowedList(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AddToAllowedList(address)"(
      _address?: PromiseOrValue<string> | null
    ): AddToAllowedListEventFilter;
    AddToAllowedList(
      _address?: PromiseOrValue<string> | null
    ): AddToAllowedListEventFilter;

    "RemoveFromAllowedList(address)"(
      _address?: PromiseOrValue<string> | null
    ): RemoveFromAllowedListEventFilter;
    RemoveFromAllowedList(
      _address?: PromiseOrValue<string> | null
    ): RemoveFromAllowedListEventFilter;
  };

  estimateGas: {
    addToAllowedList(
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    checkAllowedList(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isInAllowedList(
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeFromAllowedList(
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addToAllowedList(
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    checkAllowedList(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isInAllowedList(
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeFromAllowedList(
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
